---
- hosts: compute
  remote_user: nick
  vars:
    mount_dir: ~/cloud
    remote_dir: /cloud
  tasks:
    - name: Install NFS
      apt:
        name: nfs-common
        state: present
      become: yes
    - name: Make Mount Dir
      file:
        path: "{{mount_dir}}"
        state: directory

    - name: Mount
      mount:
        path: "mount_dir"
        src: "192.168.0.127:{{remote_dir}}"
