---
- hosts: compute
  name: Setup Compute Node
  remote_user: nick
  roles:
   - mpi
- hosts: master_node
  name: setup mpicc
  remote_user: nick
  roles:
  - mpicc
  - ansible_master
  - mpi
- hosts: storage
  name: Setup Storage Server
  remote_user: nick
  roles:
  - storage