---
- hosts: compute master_node
  name: Setup Compute Node
  remote_user: nick
  roles:
   - mpi
- hosts: master_node
  name: setup mpicc
  remote_user: nick
  roles:
  - mpicc
- hosts: storage
  name: Setup Storage Server
  remote_user: nick
  tasks:
  - name: Install Python
    apt:
      name: python
      state: present
    become: yes
  - name: Install NFS
    apt:
      name: nfs-kernel-server
      state: present
    become: yes
  - name: Make Shared Directory
    file:
      path: "{{remote_dir}}"
      state: directory
      mode: 0775
    become: yes
  - name: Copy Exports File
    copy:
      src: exports
      dest: /etc/exports
      owner: root
      group: root
      mode: 0644
    become: yes
  - name: Start NFS
    service:
      name: nfs-kernel-server
      state: started

    become: yes
